#!/bin/bash
outp=$(sensors)
acpit=$(echo "$outp" | grep "temp3: " | awk '{print substr($2,2,2)}')
cput=$(echo "$outp" | grep "Package id 0:" | awk '{print substr($4,2,2)}')
echo -e "ACPI: $acpit°C CPU: $cput°C"
