#!/bin/sh

cp ~/.config/fish/config.fish artix/confs/config.fish
cp ~/.config/i3/config artix/confs/conf.i3
cp ~/.config/sx/sxrc artix/confs/sxrc
cp ~/.config/nvim/init.vim neovim/init.vim
cp -rT ~/scr scr
