#!/bin/bash
#stupid ass printf %3s doesnt work on bash?
# cpu calc: https://stackoverflow.com/questions/26791240/how-to-get-percentage-of-processor-use-with-bash
i=118
updv=''
diskv=''
while :; do
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_prev=$((user+system+nice+softirq+steal))
    cpu_total_prev=$((user+system+nice+softirq+steal+idle+iowait))
    sleep 1
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_cur=$((user+system+nice+softirq+steal))
    cpu_total_cur=$((user+system+nice+softirq+steal+idle+iowait))
    cpu_util=$((100*(cpu_active_cur-cpu_active_prev)/(cpu_total_cur-cpu_total_prev)))
    cpu_outp=`printf %3s $cpu_util`
    mod=$(expr $i % 120)
    if [ $mod -eq 0 ]
    then
        updv=$(~/scr/modules/updates-mod)
        diskv=$(~/scr/modules/disk-mod)
    fi
    sensv=$(~/scr/modules/sensor-mod)
    wifiv=$(~/scr/modules/wifi-mod)
    memv=$(~/scr/modules/mem-mod)
    dtv=$(~/scr/modules/dt-mod)

    outp="%{W$BAR_HEIGHT}%{l}%{B-}%{F-}%{Zt<}%{B#80000000}%{F#fff}"
    outp+="%{B-}%{F-}%{Zt>}%{B#00000000}%{F#fff}"
    outp+="%{c}%{B-}%{F#80d53924}%{Zt<}%{B#80d53924}%{F#fff} "
    outp+="$sensv "
    outp+="%{F#8078d127}%{Zs<}%{F#fff}"
    outp+="%{B#8078d127} $diskv "
    outp+="%{F#80f57900}%{Zs<}%{F#fff}"
    outp+="%{B#80f57900} $wifiv "
    outp+="%{F#802a42ca}%{Zs<}%{F#fff}"
    outp+="%{B#802a42ca}$memv "
    outp+="%{F#80cc2cb3}%{Zs<}%{F#fff}"
    outp+="%{B#80cc2cb3} $cpu_outp% "
    outp+="%{B-}%{F#80cc2cb3}%{Zt>}%{B#00000000}%{F#fff}"
    outp+="%{r}%{B-}%{F-}%{Zt<}%{B#80000000}%{F#fff}"
    outp+=" $dtv "
    outp+="%{B-}%{F-}%{Zt>}"
    echo "$outp"

    ((i++))
done
