#!/bin/sh
printf "\033[31mThis action will close the path to reikai and all content will be lost!\033[0m"
doas -L
# ensure content is gone even if it fumbles with umount so it can't remove reikai itself
doas rm -rf /mnt/reikai/*
doas umount /mnt/reikai
sync
doas rm -rf /mnt/reikai
printf "\033[35mreikai\033[0m: \033[32mclosed\033[0m and it's content is \033[31mgone\033[0m."
