#!/bin/sh

# flush
iptables -F

# default to drop
iptables --policy INPUT DROP
iptables --policy OUTPUT DROP
iptables --policy FORWARD DROP

# accept related or established connections
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# accept loopback
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# accept outbound DHCP
iptables -A OUTPUT -p udp --dport 67:68 -j ACCEPT

# accept outbound DNS
iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

# accept outbound HTTP/HTTPS
iptables -A OUTPUT -p tcp -m tcp --dport 80 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 443 -m state --state NEW -j ACCEPT

# accept SSH server
iptables -A OUTPUT -p tcp -m tcp --dport 22 -j ACCEPT

# accept outbound ping
iptables -A OUTPUT -p icmp -j ACCEPT

# accept outbound NTP
# iptables -A OUTPUT -p udp --dport 123 -j ACCEPT

# accept outbound SMTP
# iptables -A OUTPUT -p tcp --dport 25 -m state --state NEW -j ACCEPT

# accept outbound IMAP/IMAPS
# iptables -A OUTPUT -p tcp --dport 143 -m state --state NEW -j ACCEPT
# iptables -A OUTPUT -p tcp --dport 993 -m state --state NEW -j ACCEPT

iptables -L -n -v

# https://dev.to/dandyvica/securing-your-linux-desktop-using-iptables-firewall-rules-3p86
