#!/bin/bash
#stupid ass printf %3s doesnt work on bash?
# cpu calc: https://stackoverflow.com/questions/26791240/how-to-get-percentage-of-processor-use-with-bash
i=118
updv=''
diskv=''
while :; do
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_prev=$((user+system+nice+softirq+steal))
    cpu_total_prev=$((user+system+nice+softirq+steal+idle+iowait))
    sleep 1
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_cur=$((user+system+nice+softirq+steal))
    cpu_total_cur=$((user+system+nice+softirq+steal+idle+iowait))
    cpu_util=$((100*(cpu_active_cur-cpu_active_prev)/(cpu_total_cur-cpu_total_prev)))
    cpu_outp=`printf %3s $cpu_util`
    mod=$(expr $i % 120)
    if [ $mod -eq 0 ]
    then
        updv=$(~/scripts/modules/updates-mod)
        diskv=$(~/scripts/modules/disk-mod)
    fi
    sensv=$(~/scripts/modules/sensor-mod)
    wifiv=$(~/scripts/modules/wifi-mod)
    memv=$(~/scripts/modules/mem-mod)
    capsv=$(~/scripts/modules/caps-mod)
    dtv=$(~/scripts/modules/dt-mod)

    outp="%{l}"
    outp+="%{B-}%{F#000000}"
    outp+="%{B#cc241d} $sensv "
    outp+="%{B-}%{O8}%{B#d79921} $diskv "
    outp+="%{B-}%{O8}%{B#98971a} $wifiv "
    outp+="%{B-}%{O8}%{B#458588} $memv "
    outp+="%{B-}%{O8}%{B#b16286} $cpu_outp% "
    outp+="%{B-}%{O8}%{B#d65d0e}$caspv%{B-}"
    outp+="%{r}%{B-}%{F#fbf1c7}"
    outp+="%{B-}%{O8}%{B#504945} $updv "
    outp+="%{B-}%{O8}%{B#3c3836} $dtv %{B-}"

    echo "$outp"

    ((i++))
done
