#!/bin/sh
doas -L
doas mkdir /mnt/reikai
doas mount ramfs -t ramfs /mnt/reikai
doas chown cody /mnt/reikai
# doas --remove-timestamp # otherwise doas password is used in scrypt (?)
scrypt dec /home/cody/git/misc/vault.zip.scrypt /mnt/reikai/vault.zip
unzip -qq /mnt/reikai/vault.zip -d /mnt/reikai/
rm /mnt/reikai/vault.zip
md5sum /mnt/reikai/vault/* | awk '{print $1}' > /mnt/reikai/.sealstamp
echo 'reikai: opened'

