#!/bin/sh
mv /home/cody/git/misc/vault.zip.scrypt /home/cody/git/misc/vault.zip.scrypt.b
sudo --remove-timestamp
cd /mnt/reikai/
zip -qq -r vault.zip vault
scrypt enc vault.zip vault.zip.scrypt
mv vault.zip.scrypt /home/cody/git/misc/vault.zip.scrypt
rm vault.zip
