#!/bin/sh
theme=$(echo 'space\nnord' | dmenu -p '')
cp ~/scripts/themes/$theme/st.sh ~/scripts/st.sh
cp ~/scripts/themes/$theme/st-float ~/scripts/st-float
cp ~/scripts/themes/$theme/shapebar-conf ~/scripts/shapebar-conf
cp ~/scripts/themes/$theme/run-shapebar ~/scripts/run-shapebar
cp ~/scripts/themes/$theme/init-background ~/scripts/init-background
cp ~/scripts/themes/$theme/Xdmenu ~/scripts/Xdmenu
~/scripts/themes/$theme/init-background
xrdb -merge ~/scripts/themes/$theme/Xdmenu
killall shapebar
~/scripts/run-shapebar &> /dev/null &
