#!/bin/sh
theme=$(echo 'space\nnord\ngruvbox\nhawkrad\ntokyo-night' | dmenu -p '')
if [ -z "$theme" ]
then
    exit;
fi
cp ~/scripts/themes/$theme/shapebar-conf ~/scripts/shapebar-conf
cp ~/scripts/themes/$theme/run-shapebar ~/scripts/run-shapebar
cp ~/scripts/themes/$theme/init-background ~/scripts/init-background
cp ~/scripts/themes/$theme/Xdmenu ~/scripts/Xdmenu
cp ~/scripts/themes/$theme/Xst ~/scripts/Xst
~/scripts/themes/$theme/init-background
xrdb -merge ~/scripts/themes/$theme/Xdmenu
xrdb -merge ~/scripts/themes/$theme/Xst
pkill -USR1 '^st$'
killall shapebar
~/scripts/run-shapebar &> /dev/null &
