#!/bin/sh
#xrandr --auto
set-theme-data

if true; then
  i3
else
  exec xrandr --output DP-0 --output HDMI-0 --right-of DP-0 &
  exec picom --xrender-sync-fence &
  exec ~/scr/.theme/run-shapebar &
  exec /home/cody/git/penrose-cody/target/release/penrose-cody
fi
