#!/bin/bash
#xrandr --auto
set-theme-data
i3

#picom --xrender-sync-fence &> /dev/null &
#xrandr --output DP-0 --output HDMI-0 --right-of DP-0 &> /dev/null &
#~/scripts/run-shapebar &> /dev/null &
#git/penrose-cody/target/debug/penrose-cody
