#!/bin/bash
#stupid ass printf %3s doesnt work on bash?
# cpu calc: https://stackoverflow.com/questions/26791240/how-to-get-percentage-of-processor-use-with-bash
i=118
updv=''
diskv=''
while :; do
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_prev=$((user+system+nice+softirq+steal))
    cpu_total_prev=$((user+system+nice+softirq+steal+idle+iowait))
    sleep 1
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_cur=$((user+system+nice+softirq+steal))
    cpu_total_cur=$((user+system+nice+softirq+steal+idle+iowait))
    cpu_util=$((100*(cpu_active_cur-cpu_active_prev)/(cpu_total_cur-cpu_total_prev)))
    cpu_outp=`printf %3s $cpu_util`
    mod=$(expr $i % 120)
    if [ $mod -eq 0 ]
    then
        updv=$(~/scripts/modules/updates-mod)
        diskv=$(~/scripts/modules/disk-mod)
    fi

    outp="%{W26}"
    outp+="%{l}"
    outp+="%{B-}"
    outp+="%{B-} %{B#BF616A}%{F-}%{Zt>}%{F#11113A} $(~/scripts/modules/wifi-mod) %{F#BF616A}%{B#3b4252}%{Zt>}"
    outp+="%{B#D08770}%{F-}%{Zt>}%{F#11113A} $(~/scripts/modules/sensor-mod) %{F#D08770}%{B#3b4252}%{Zt>}"
    outp+="%{B#A3BE8C}%{F-}%{Zt>}%{F#11113A} $diskv %{F#A3BE8C}%{B#3b4252}%{Zt>}"
    outp+="%{B#5E81AC}%{F-}%{Zt>}%{F#11113A} $cpu_outp% %{F#5E81AC}%{B#3b4252}%{Zt>}"
    outp+="%{B#B48EAD}%{F-}%{Zt>}%{F#11113A} $(~/scripts/modules/mem-mod) %{F#B48EAD}%{B#3b4252}%{Zt>}"
    outp+="%{B-}"
    outp+="%{r}"
    outp+="%{B#434c5e}%{F-}%{Zt>}%{F#ECEFF4}$(~/scripts/modules/caps-mod)%{F#434c5e}%{B-}%{Zt>}"
    outp+="%{B#434c5e}%{F-}%{Zt>}%{F#ECEFF4} $updv %{F#434c5e}%{B-}%{Zt>}"
    outp+="%{B#4c566a}%{F-}%{Zt>}%{F#ECEFF4} $(~/scripts/modules/dt-mod) %{F#4c566a}%{B-}%{Zt>} "

    echo "$outp"

    ((i++))
done
